name: "go-install-script"
description: "quick and dirty install for golang on linux workflows"
inputs:
  architecture:
    description: "linux architecture to use for Go files (e.g. amd64)"
    required: true
  purge:
    description: "delete any previously installed go versions"
    required: false
    default: "no"
runs:
  using: composite
  steps:
    - name: "run script"
      run: ${{ github.action_path }}/go.sh ${{ inputs.architecture }} ${{ inputs.purge }}
      shell: bash
