name: 'go-install-script'
description: 'Quickly install golang for linux workflows'
runs:
  using: composite
  steps:
    - name: "i hate this"
      run: ls
      shell: bash
      
    - name: "run script"
      run: ./go.sh
      shell: bash
