name: "go-install-test"
run-name: "go-install-test"
on:
  push:
    branches: master
    paths: go.sh

jobs:
  test:
    runs-on: [ubuntu-22.04]
    steps:
      - name: "setup mock go.mod file"
        shell: bash
        run: |
          echo -e "module github.com/jake-young-dev/go-install-script\n\ngo 1.23.5" > go.mod

      - name: "run go install script"
        uses: jake-young-dev/go-install-script@master
        with:
          architecture: amd64
          overwrite: yes #removes old go versions if present (github hosted runners come preloaded with go)
