name: "go-install-test"
run-name: "go-install-test"
on:
  push:
    branches: master

jobs:
  test:
    runs-on: [ubuntu-22.04]
    steps:
      - name: "setup env and remove cached go"
        shell: bash
        run: |  #images come with go preloaded on github hosted runners, removing for tests
          echo -e "module github.com/jake-young-dev/go-install-script\n\ngo 1.23.5" > go.mod

      - name: "run go script"
        uses: jake-young-dev/go-install-script@master
        with:
          architecture: amd64
          overwrite: yes