name: "go-install-test"

on:
  push:
    branches: master
    paths: go.sh

jobs:
  install-test:
    runs-on: [ubuntu-latest]
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v4
      
      - name: "run script"
        shell: bash
        run: |
          chmod +x ./go.sh
          sudo echo -e "module github.com/jake-young-dev/go-install-script\n\ngo 1.23.5" > go.mod
          sudo ./go.sh ${{ vars.GO_TEST_ARCH }}
