name: "tests"
run-name: "tests"
on:
  push:
    branches: master
    paths: 
      - go.sh
      - action.yaml
      - .github/test.yaml #changing pipeline triggers run

jobs:
  test:
    runs-on: [ubuntu-22.04]
    steps:
      - name: "setup mock go.mod file"
        shell: bash
        run: |
          echo -e "module github.com/jake-young-dev/go-install-script\n\ngo 1.23" > go.mod

      - name: "run go install script"
        uses: jake-young-dev/go-install-script@master
        with:
          architecture: amd64
          purge: yes #removes old go versions if present (github hosted runners come preloaded with go)

      - name: "check go version"
        shell: bash
        run: go version
